CREATE TABLE [dbo].[Personnage]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Nom] NVARCHAR(50) NOT NULL,
	[PvMax] INT NOT NULL CHECK(PvMax <= 9999),
	[DateDeCreation] DATETIME2 NOT NULL,
	[ViVant] BIT NOT NULL,
	[JobId] INT NOT NULL REFERENCES Job
)
